name: Workshop Test

on: 
  workflow_dispatch:

jobs:
  workshop-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Create build folder
        run: mkdir build

      - name: Retrieve cache
        uses: actions/checkout@v4
        with:
          ref: cache
          path: build

      - name: Examine folder structure
        run: ls -a -R
